"""Add projects and certifications to resume

Revision ID: add766552177
Revises: 
Create Date: 2026-07-28 23:26:24.767647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add766552177'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projects', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('certifications')
        batch_op.drop_column('projects')

    # ### end Alembic commands ###
